### ISSUE TITLE
With the same package "mods.psi.Trick" with gugu-utils

### ISSUE THREAD

**Issue by mczph** [ISurrealI/TTweaker#3]
Trick is already defined in that package
https://github.com/ParaParty/gugu-utils/blob/main/src/main/java/com/warmthdawn/mod/gugu_utils/crafttweaker/psi/TrickInfusionRecipe.java

https://github.com/ISurrealI/TTweaker/blob/main/src/main/java/surreal/ttweaker/integration/psi/CTTrick.java

**Comment by ISurrealI** [comment]
Removed Psi support. I will gonna add support to my psi fork (and check if gugu utils is loaded or not). It would be cool if you asked them to remove the support because recipes don't work on the final 1.12.2 release (it was fixed in github but fixed version isn't released) and my fork is the version with that fix.
